---
stages:
  - puppetfilecheck

default:
  image: ruby:latest
  cache:
    paths:
      - vendor/ruby

  before_script:
    - ruby -v  # Print out ruby version for debugging
    - bundle -v
    - gem --version
    - rm Gemfile.lock || true
    - bundle config set --local deployment true  # Install dependencies into ./vendor/ruby
    - bundle config set --path vendor/ruby
    - bundle install -j $(nproc)

puppetfilecheck:
  script:
    - scripts/codecheck.rb Puppetfile
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - Puppetfile
